sudo: required
services:
  - docker


before_install: 
  - docker build -t rajashekar435/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rajashekar435/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env-3"
  bucket_name: "elasticbeanstalk-us-east-2-850255941497"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY